import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";
import { AuthProvider } from "@/domains/auth/context/AuthContext";
import { AppProvider } from "@/domains/auth/context/AppContext";
import { AttendanceProvider } from "@/domains/attendance/context/AttendanceContext";
import { PayrollProvider } from "@/domains/payroll/context/PayrollContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <AppProvider>
            <AttendanceProvider>
              <PayrollProvider>
                {children}
              </PayrollProvider>
            </AttendanceProvider>
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
